Jeremiah
enocknkhoma/IESAM360-WEB pull request #1
Opened 2023-02-26 22:20 UTC by wannaBeKakashi

Remaining with tests.

2023-02-27 00:21 UTC, enocknkhoma requested changes
@wannaBeKakashi , please look at the attached comments

2023-02-27 00:21 UTC, enocknkhoma commented on app/Http/Controllers/Api/CourseController.php
> +        $course = Course::all();
Rename $course to $courses  on line # 23

2023-02-27 00:21 UTC, enocknkhoma commented on app/Http/Controllers/Api/CourseController.php
> +        $create_course = $request->post();
rename create $create_course to $data line #41

2023-02-27 00:21 UTC, enocknkhoma commented on app/Http/Controllers/Api/CourseController.php
> +    public function show(string $id)
The show method should return the Resource wit that ID

2023-02-27 00:21 UTC, enocknkhoma commented on app/Http/Controllers/Api/CourseController.php
> +    public function edit(string $id)
Remove the show and edit method

2023-02-27 00:21 UTC, enocknkhoma commented on app/Http/Controllers/Api/CourseController.php
> +    public function update(UpdateRequest $request, string $id)
an update should return the resource 
rename $update_course to $updates

2023-02-27 00:21 UTC, enocknkhoma commented on app/Http/Requests/CourseComment/CreateRequest.php
> +        return [
user id and course id are also required

2023-02-27 00:21 UTC, enocknkhoma commented on routes/api.php
>  });
Use middleware group to group all routes that requires sanctum

2023-02-27 00:21 UTC, enocknkhoma commented on app/Http/Resources/ContentCommentResource.php
> +
Put the resources in their own name space 
i.e CourseResource goes to Resources/Course/CourseResource

2023-02-27 00:25 UTC, enocknkhoma requested changes

2023-02-27 00:25 UTC, enocknkhoma commented on tests/Feature/ContentCommentTest.php
> +    public function test_can_list_all_content_comments(): void
Chief, how are you authenticating the user making the request to the APIs in the test. ? 
Look at how this was implemented in the ES_MMS

2023-02-27 00:25 UTC, enocknkhoma commented on tests/Feature/CourseContentTest.php
> +        $course_content = CourseContent::factory()->make()->toArray();
rename $course_content to $data

2023-02-27 00:25 UTC, enocknkhoma commented on tests/Feature/CourseContentTest.php
> +        $course_content = CourseContent::factory()->create();
rename course_update to $updates

2023-02-27 00:29 UTC, enocknkhoma commented
@wannaBeKakashi , so let's close the above issues and then we close on this one

2023-02-27 08:25 UTC, wannaBeKakashi commented on routes/api.php
>  });
An error comes which i include sanctum

2023-02-27 08:25 UTC, wannaBeKakashi commented on routes/api.php
>  });
when*

2023-03-04 21:09 UTC, enocknkhoma approved these changes

2023-03-04 21:09 UTC, merged